# -*- coding: utf-8 -*-
"""findcounting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tQ7EhsNJUFduWiQFqOAg45dMLYc09Exw
"""

!pip install mediapipe opencv-python

# Gerekli kütüphaneleri yükleyin
from google.colab.patches import cv2_imshow
import cv2
import numpy as np
from IPython.display import display, Javascript
from google.colab import output
from PIL import Image
import base64
from io import BytesIO
import mediapipe as mp

# JavaScript ile video başlatma
def start_camera():
    display(Javascript('''
        async function captureImage() {
            const video = document.createElement('video');
            video.width = 640;
            video.height = 480;
            video.autoplay = true;
            video.style.display = 'none';

            const stream = await navigator.mediaDevices.getUserMedia({ video: true });
            document.body.appendChild(video);
            video.srcObject = stream;

            await new Promise((resolve) => video.onplaying = resolve);

            // Frame alıp Python'a gönder
            setInterval(() => {
                const canvas = document.createElement('canvas');
                canvas.width = video.width;
                canvas.height = video.height;
                const context = canvas.getContext('2d');
                context.drawImage(video, 0, 0, video.width, video.height);

                // Görüntüyü veri URL'si olarak al
                const dataUrl = canvas.toDataURL('image/jpeg');
                google.colab.kernel.invokeFunction('notebook.capture', [dataUrl], {});
            }, 100);  // her 100ms'de bir frame al
        }
        captureImage();
    '''))

# Python tarafında görüntü yakalama ve işleme
def capture(dataUrl):
    img_data = base64.b64decode(dataUrl.split(',')[1])
    img = Image.open(BytesIO(img_data))

    # Görüntüyü numpy array'e dönüştürme
    img_np = np.array(img)
    img_np = cv2.cvtColor(img_np, cv2.COLOR_RGB2BGR)

    # Mediapipe işlemleri başlatılıyor
    mpHand = mp.solutions.hands
    hands = mpHand.Hands()
    mpDraw = mp.solutions.drawing_utils

    tipIds = [4, 8, 12, 16, 20]
    imgRGB = cv2.cvtColor(img_np, cv2.COLOR_BGR2RGB)

    # El izleme işlemi
    results = hands.process(imgRGB)
    lmList = []
    if results.multi_hand_landmarks:
        for handLms in results.multi_hand_landmarks:
            mpDraw.draw_landmarks(img_np, handLms, mpHand.HAND_CONNECTIONS)

            for id, lm in enumerate(handLms.landmark):
                h, w, _ = img_np.shape
                cx, cy = int(lm.x*w), int(lm.y*h)
                lmList.append([id, cx, cy])

    if len(lmList) != 0:
        fingers = []

        # Baş parmak
        if lmList[tipIds[0]][1] < lmList[tipIds[0] - 1][1]:
            fingers.append(1)
        else:
            fingers.append(0)

        # Diğer parmaklar
        for id in range(1, 5):
            if lmList[tipIds[id]][2] < lmList[tipIds[id] - 2][2]:
                fingers.append(1)
            else:
                fingers.append(0)

        totalF = fingers.count(1)
        cv2.putText(img_np, str(totalF), (30,125), cv2.FONT_HERSHEY_PLAIN, 10, (255,0,0),8)

    # Görüntüyü gösterme
    cv2_imshow(img_np)
    cv2.waitKey(1)  # Video sürekli akıyor, her frame'i göstermek için

# Kameradan sürekli görüntü alma başlat
start_camera()

# Python tarafında görüntü alındığında 'capture' fonksiyonunu çağırır
output.register_callback('notebook.capture', capture)